name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  # authentication_repository:
  #   path: packages/authentication_repository
  bloc: ^8.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.3
  transparent_image: ^1.0.0   
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  google_maps_flutter: ^2.2.0
  sqflite: any
  path_provider: any
  image_picker: ^0.8.4+2
  http: ^0.13.5
  json_serializable: ^6.3.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  formz: ^0.4.1
  firebase_messaging: ^13.1.0
  very_good_analysis: ^3.0.2
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.3.4
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.9
  cloud_functions: ^3.3.9
  flutter_signin_button: ^2.0.0
  email_validator: ^2.0.1
  google_sign_in: ^5.4.1
 
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/iconoelestanco.png
    - images/opium.png
    - images/PABLOESTANCO.png
    - images/crobarestanco.png
    - images/logo.png
    - images/login.png
    - images/google.png
    - images/este.png
    - images/oeste.png
    - images/norte.png
    - images/sur.png
    - images/aguila.png
    - images/poker.png
    - images/costeña.png
    - images/corona.png
    - images/licor1.png
    - images/aguar.png
    - images/vino.png
    - images/smirnoff.png
    - images/redbull.png
    - images/malboro.png
    - images/mechera.png
    - images/noimage.png


  

fonts:
  -family: Acme
  fonts:
    -asset: fonts/Acme-Regular.ttf